# Generated by Django 6.1.1 on 2026-10-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_quality',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_source',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
